name: interactkids
version: 1.0.0+1
description: Children's Interactive Learning App
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image: ^4.0.17
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.2
  just_audio: ^0.9.36
  provider: ^6.1.2
  image_picker: ^1.0.7
  confetti: ^0.7.0
  image_cropper: ^10.0.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/puzzle/
    - assets/images/fruits/
    - assets/images/fruits/Fruits/
    - assets/images/vegetables/
    - assets/processed/
    - assets/processed/fruits/
    - assets/processed/vegetables/
    - assets/audio/brycen/
    - assets/audio/yliana/
    - assets/audio/kaida/
    - assets/images/mascot.png
    - assets/fonts/
    - assets/audio/sfx/
    - assets/images/characters/brycen.png
    - assets/images/characters/yliana.png
    - assets/images/characters/kaida.png
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
